version: 2
updates:
  # Update Docker base images
  - package-ecosystem: "docker"
    directory: "/octofree"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    # Create PRs against master - branch protection will prevent auto-merge
    target-branch: "master"
    reviewers:
      - "dopeytree"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Update Python dependencies
  - package-ecosystem: "pip"
    directory: "/octofree"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    # Create PRs against master - branch protection will prevent auto-merge
    target-branch: "master"
    reviewers:
      - "dopeytree"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    # Create PRs against master - branch protection will prevent auto-merge
    target-branch: "master"
    reviewers:
      - "dopeytree"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"