name: Auto-approve Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Build and test
      run: |
        cd octofree
        docker build -t octofree .

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scan-ref: 'octofree'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Check for critical vulnerabilities
      run: |
        # Parse Trivy results and fail if critical/high vulnerabilities found
        if grep -q '"severity":\s*"CRITICAL\|HIGH"' trivy-results.sarif; then
          echo "❌ Critical or High vulnerabilities found, will not auto-approve"
          exit 1
        fi

    - name: Auto-approve PR
      if: success()
      run: gh pr review --approve ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Add comment
      if: success()
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "✅ Automated tests passed and no critical vulnerabilities found. This PR is approved but requires manual merge due to branch protection rules."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}