name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and test
      run: |
        cd octofree
        docker build -t octofree .

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        scan-ref: 'octofree'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Check for critical vulnerabilities
      run: |
        # Parse Trivy results and fail if critical/high vulnerabilities found
        if grep -q '"severity":\s*"CRITICAL\|HIGH"' trivy-results.sarif; then
          echo "Critical or High vulnerabilities found, not auto-merging"
          exit 1
        fi

    - name: Auto-merge PR
      if: success()
      run: gh pr merge --auto --squash ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}